<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pedro Perilla">

<title>Taller 1 – Sistemas de Coordenadas en Colombia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="taller_sistemas_coordenadas_files/libs/clipboard/clipboard.min.js"></script>
<script src="taller_sistemas_coordenadas_files/libs/quarto-html/quarto.js"></script>
<script src="taller_sistemas_coordenadas_files/libs/quarto-html/popper.min.js"></script>
<script src="taller_sistemas_coordenadas_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="taller_sistemas_coordenadas_files/libs/quarto-html/anchor.min.js"></script>
<link href="taller_sistemas_coordenadas_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="taller_sistemas_coordenadas_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="taller_sistemas_coordenadas_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="taller_sistemas_coordenadas_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="taller_sistemas_coordenadas_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#contexto-general" id="toc-contexto-general" class="nav-link active" data-scroll-target="#contexto-general"><span class="header-section-number">1</span> Contexto General</a></li>
  <li><a href="#procedimientos-realizados" id="toc-procedimientos-realizados" class="nav-link" data-scroll-target="#procedimientos-realizados"><span class="header-section-number">2</span> Procedimientos realizados</a>
  <ul class="collapse">
  <li><a href="#verificación-del-shapefile-cundinamarca.shp" id="toc-verificación-del-shapefile-cundinamarca.shp" class="nav-link" data-scroll-target="#verificación-del-shapefile-cundinamarca.shp"><span class="header-section-number">2.1</span> Verificación del Shapefile cundinamarca.shp</a></li>
  <li><a href="#definir-el-sistema-de-coordenadas-para-una-capa-sin-sistema-definido" id="toc-definir-el-sistema-de-coordenadas-para-una-capa-sin-sistema-definido" class="nav-link" data-scroll-target="#definir-el-sistema-de-coordenadas-para-una-capa-sin-sistema-definido"><span class="header-section-number">2.2</span> Definir el sistema de coordenadas para una capa sin sistema definido</a>
  <ul class="collapse">
  <li><a href="#sistema-gcs_bogota" id="toc-sistema-gcs_bogota" class="nav-link" data-scroll-target="#sistema-gcs_bogota"><span class="header-section-number">2.2.1</span> Sistema GCS_Bogota</a></li>
  </ul></li>
  <li><a href="#definir-el-sistema-de-coordenadas-para-el-shapefile-veredas.shp" id="toc-definir-el-sistema-de-coordenadas-para-el-shapefile-veredas.shp" class="nav-link" data-scroll-target="#definir-el-sistema-de-coordenadas-para-el-shapefile-veredas.shp"><span class="header-section-number">2.3</span> Definir el sistema de coordenadas para el Shapefile veredas.shp</a>
  <ul class="collapse">
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">2.3.1</span> Análisis</a></li>
  </ul></li>
  <li><a href="#sistema-colombia-bogota-zone" id="toc-sistema-colombia-bogota-zone" class="nav-link" data-scroll-target="#sistema-colombia-bogota-zone"><span class="header-section-number">2.4</span> Sistema Colombia Bogota Zone</a>
  <ul class="collapse">
  <li><a href="#propiedades" id="toc-propiedades" class="nav-link" data-scroll-target="#propiedades"><span class="header-section-number">2.4.1</span> Propiedades</a></li>
  </ul></li>
  <li><a href="#sistemas-oficiales-en-colombia" id="toc-sistemas-oficiales-en-colombia" class="nav-link" data-scroll-target="#sistemas-oficiales-en-colombia"><span class="header-section-number">2.5</span> Sistemas Oficiales en Colombia</a>
  <ul class="collapse">
  <li><a href="#magna-sirgas-2018-origen-nacional" id="toc-magna-sirgas-2018-origen-nacional" class="nav-link" data-scroll-target="#magna-sirgas-2018-origen-nacional"><span class="header-section-number">2.5.1</span> MAGNA-SIRGAS 2018 / Origen Nacional</a></li>
  <li><a href="#tabla-de-sistemas-de-coordenadas-en-colombia" id="toc-tabla-de-sistemas-de-coordenadas-en-colombia" class="nav-link" data-scroll-target="#tabla-de-sistemas-de-coordenadas-en-colombia"><span class="header-section-number">2.5.2</span> Tabla de Sistemas de Coordenadas en Colombia</a></li>
  </ul></li>
  <li><a href="#transformación-de-sistemas-de-coordenadas-en-arcgis-pro" id="toc-transformación-de-sistemas-de-coordenadas-en-arcgis-pro" class="nav-link" data-scroll-target="#transformación-de-sistemas-de-coordenadas-en-arcgis-pro"><span class="header-section-number">2.6</span> Transformación de sistemas de coordenadas en ArcGIS Pro</a>
  <ul class="collapse">
  <li><a href="#resultado-de-la-reproyección" id="toc-resultado-de-la-reproyección" class="nav-link" data-scroll-target="#resultado-de-la-reproyección"><span class="header-section-number">2.6.1</span> Resultado de la reproyección</a></li>
  </ul></li>
  <li><a href="#usando-la-proyección-al-vuelo" id="toc-usando-la-proyección-al-vuelo" class="nav-link" data-scroll-target="#usando-la-proyección-al-vuelo"><span class="header-section-number">2.7</span> Usando la Proyección al Vuelo</a>
  <ul class="collapse">
  <li><a href="#resultado-formalizado" id="toc-resultado-formalizado" class="nav-link" data-scroll-target="#resultado-formalizado"><span class="header-section-number">2.7.1</span> Resultado formalizado</a></li>
  </ul></li>
  <li><a href="#conversión-importando-a-una-geodatabase" id="toc-conversión-importando-a-una-geodatabase" class="nav-link" data-scroll-target="#conversión-importando-a-una-geodatabase"><span class="header-section-number">2.8</span> Conversión importando a una Geodatabase</a>
  <ul class="collapse">
  <li><a href="#creación-del-dataset" id="toc-creación-del-dataset" class="nav-link" data-scroll-target="#creación-del-dataset"><span class="header-section-number">2.8.1</span> Creación del Dataset</a></li>
  <li><a href="#importación-de-veredas-al-dataset" id="toc-importación-de-veredas-al-dataset" class="nav-link" data-scroll-target="#importación-de-veredas-al-dataset"><span class="header-section-number">2.8.2</span> Importación de veredas al Dataset</a></li>
  </ul></li>
  <li><a href="#generar-una-capa-de-puntos-desde-lista-de-coordenadas" id="toc-generar-una-capa-de-puntos-desde-lista-de-coordenadas" class="nav-link" data-scroll-target="#generar-una-capa-de-puntos-desde-lista-de-coordenadas"><span class="header-section-number">2.9</span> Generar una capa de puntos desde lista de coordenadas</a>
  <ul class="collapse">
  <li><a href="#resultado-de-la-generación-de-puntos" id="toc-resultado-de-la-generación-de-puntos" class="nav-link" data-scroll-target="#resultado-de-la-generación-de-puntos"><span class="header-section-number">2.9.1</span> Resultado de la generación de puntos</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">2.10</span> Conclusiones</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="taller_sistemas_coordenadas.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller 1 – Sistemas de Coordenadas en Colombia</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Pedro Perilla </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">23 de febrero de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="contexto-general" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Contexto General</h1>
<p>Los sistemas de referencia espacial permiten ubicar con precisión cualquier punto sobre la superficie terrestre.<br>
En Colombia, la evolución de los sistemas geodésicos ha pasado del datum <strong>Bogotá 1975</strong> al marco oficial actual <strong>MAGNA-SIRGAS</strong>.</p>
<p>La correcta identificación del sistema de coordenadas es fundamental para evitar errores en cálculos de distancia, área y superposición espacial.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Trabajar con sistemas de referencia incorrectos puede generar desplazamientos espaciales de varios metros.</p>
</div>
</div>
<hr>
</section>
<section id="procedimientos-realizados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Procedimientos realizados</h1>
<p>Se utilizó <strong>ArcGIS Pro</strong> para realizar tareas relacionadas con la definición, transformación y conversión entre sistemas de coordenadas.</p>
<p>Los datos fueron suministrados en la carpeta <code>data</code>, archivo <code>coordenadas.zip</code>.<br>
Se creó un proyecto nuevo y se vinculó la ruta de datos al mismo.</p>
<p>En el catálogo se verificaron las propiedades de todos los archivos para determinar si tenían sistema de coordenadas asignado.</p>
<hr>
<section id="verificación-del-shapefile-cundinamarca.shp" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="verificación-del-shapefile-cundinamarca.shp"><span class="header-section-number">2.1</span> Verificación del Shapefile cundinamarca.shp</h2>
<p>Se evidenció que <code>cundinamarca.shp</code> no tenía sistema definido, ya que no existía el archivo <code>.prj</code>.</p>
<p>Un Shapefile está compuesto por:</p>
<ul>
<li><code>.shp</code> → geometría<br>
</li>
<li><code>.shx</code> → índice<br>
</li>
<li><code>.dbf</code> → atributos<br>
</li>
<li><code>.prj</code> → sistema de coordenadas<br>
</li>
<li><code>.cpg</code> → codificación (opcional)</li>
</ul>
<p>La ausencia del <code>.prj</code> implica que el sistema no estaba documentado.</p>
<hr>
</section>
<section id="definir-el-sistema-de-coordenadas-para-una-capa-sin-sistema-definido" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="definir-el-sistema-de-coordenadas-para-una-capa-sin-sistema-definido"><span class="header-section-number">2.2</span> Definir el sistema de coordenadas para una capa sin sistema definido</h2>
<p>Se utilizó la herramienta:</p>
<p><strong>Data Management Tools → Projections and Transformations → Define Projection</strong></p>
<ul>
<li>Input Dataset: <code>Cundinamarca.shp</code></li>
<li>Coordinate System: <strong>GCS_Bogota</strong></li>
<li>Ejecutar con “Run”</li>
</ul>
<hr>
<section id="sistema-gcs_bogota" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="sistema-gcs_bogota"><span class="header-section-number">2.2.1</span> Sistema GCS_Bogota</h3>
<ul>
<li>Tipo: Geográfico<br>
</li>
<li>Datum: Bogotá 1975<br>
</li>
<li>Elipsoide: International 1924<br>
</li>
<li>EPSG: 4218</li>
</ul>
<p>No está relacionado con MAGNA-SIRGAS ni con ARENA.<br>
Es un sistema geográfico basado en datum local antiguo.</p>
<hr>
</section>
</section>
<section id="definir-el-sistema-de-coordenadas-para-el-shapefile-veredas.shp" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="definir-el-sistema-de-coordenadas-para-el-shapefile-veredas.shp"><span class="header-section-number">2.3</span> Definir el sistema de coordenadas para el Shapefile veredas.shp</h2>
<p>Para <code>veredas.shp</code> se verificó:</p>
<ul>
<li>Tipo: Proyectado<br>
</li>
<li>Datum: Bogotá 1975<br>
</li>
<li>Proyección: Transverse Mercator<br>
</li>
<li>EPSG: 21891</li>
</ul>
<p>No pertenece a los seis orígenes oficiales de MAGNA-SIRGAS.<br>
Corresponde al sistema plano antiguo cuyo origen estaba definido en Bogotá.</p>
<hr>
<section id="análisis" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="análisis"><span class="header-section-number">2.3.1</span> Análisis</h3>
<p>El sistema <strong>GCS_Bogota</strong> es un sistema de coordenadas geográfico basado en el datum Bogotá 1975.<br>
No corresponde al marco oficial actual del país.</p>
<p>No está relacionado con MAGNA-SIRGAS ni con el sistema ARENA, ya que estos utilizan el datum moderno adoptado oficialmente en Colombia.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Al estar basado en un datum antiguo, puede presentar diferencias significativas frente a MAGNA-SIRGAS.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="sistema-colombia-bogota-zone" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sistema-colombia-bogota-zone"><span class="header-section-number">2.4</span> Sistema Colombia Bogota Zone</h2>
<section id="propiedades" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="propiedades"><span class="header-section-number">2.4.1</span> Propiedades</h3>
<ul>
<li><strong>Tipo:</strong> Proyectado<br>
</li>
<li><strong>Datum base:</strong> Bogotá 1975<br>
</li>
<li><strong>Proyección:</strong> Transverse Mercator<br>
</li>
<li><strong>Código EPSG:</strong> 21891</li>
</ul>
<section id="análisis-1" class="level4" data-number="2.4.1.1">
<h4 data-number="2.4.1.1" class="anchored" data-anchor-id="análisis-1"><span class="header-section-number">2.4.1.1</span> Análisis</h4>
<p>El sistema <strong>Colombia Bogota Zone</strong> es un sistema proyectado derivado del datum Bogotá 1975.</p>
<p>No pertenece a los seis orígenes oficiales definidos bajo MAGNA-SIRGAS.<br>
Corresponde al sistema plano antiguo cuyo origen se encontraba en Bogotá.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este sistema fue ampliamente utilizado antes de la adopción oficial de MAGNA-SIRGAS.</p>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="sistemas-oficiales-en-colombia" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sistemas-oficiales-en-colombia"><span class="header-section-number">2.5</span> Sistemas Oficiales en Colombia</h2>
<p>Actualmente, el sistema oficial adoptado en Colombia es <strong>MAGNA-SIRGAS</strong>, el cual inicialmente definía seis orígenes cartográficos para el territorio continental e insular.</p>
<p>Sin embargo, a partir del año 2020 Colombia adoptó un <strong>Origen Nacional único</strong>, con el fin de:</p>
<ul>
<li>Garantizar continuidad espacial</li>
<li>Eliminar ambigüedades entre zonas</li>
<li>Simplificar la gestión cartográfica</li>
<li>Facilitar la interoperabilidad</li>
<li>Optimizar tiempos y costos en tratamiento de datos geográficos</li>
</ul>
<p>Este cambio fue oficializado mediante la Resolución IGAC 471 del 14 de mayo de 2020.</p>
<hr>
<section id="magna-sirgas-2018-origen-nacional" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="magna-sirgas-2018-origen-nacional"><span class="header-section-number">2.5.1</span> MAGNA-SIRGAS 2018 / Origen Nacional</h3>
<ul>
<li><strong>Tipo:</strong> Proyectado<br>
</li>
<li><strong>EPSG:</strong> 9377<br>
</li>
<li><strong>Proyección:</strong> Transversa de Mercator<br>
</li>
<li><strong>Elipsoide:</strong> GRS80</li>
</ul>
<section id="parámetros-oficiales" class="level4" data-number="2.5.1.1">
<h4 data-number="2.5.1.1" class="anchored" data-anchor-id="parámetros-oficiales"><span class="header-section-number">2.5.1.1</span> Parámetros oficiales</h4>
<table class="table">
<thead>
<tr class="header">
<th>Parámetro</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Latitud de origen</td>
<td>4° N</td>
</tr>
<tr class="even">
<td>Longitud de origen</td>
<td>73° W</td>
</tr>
<tr class="odd">
<td>Falso Este</td>
<td>5,000,000 m</td>
</tr>
<tr class="even">
<td>Falso Norte</td>
<td>2,000,000 m</td>
</tr>
<tr class="odd">
<td>Factor de escala</td>
<td>0.9992</td>
</tr>
<tr class="even">
<td>Unidades</td>
<td>Metros</td>
</tr>
</tbody>
</table>
<p>El origen se localiza cerca de Puerto López (Meta).<br>
El falso Este y falso Norte fueron definidos para evitar valores negativos y diferenciar claramente coordenadas Norte y Este.</p>
</section>
<section id="imagen-de-referencia" class="level4" data-number="2.5.1.2">
<h4 data-number="2.5.1.2" class="anchored" data-anchor-id="imagen-de-referencia"><span class="header-section-number">2.5.1.2</span> Imagen de referencia</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="origen_nacional_de_coordenadas_col.jpg" class="img-fluid figure-img"></p>
<figcaption>Origen Nacional de Coordenadas en Colombia</figcaption>
</figure>
</div>
<p>Fuente: Rodolfo Franco Web – <em>MAGNA-SIRGAS Origen Nacional</em>.<br>
Disponible en: https://rodolfofrancoweb.com/sig/proyecciones_y_sistemas_de_coordenadas/magna-sirgas-origen-nacional/</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>El Origen Nacional reemplaza progresivamente los sistemas antiguos basados en Bogotá 1975.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="tabla-de-sistemas-de-coordenadas-en-colombia" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="tabla-de-sistemas-de-coordenadas-en-colombia"><span class="header-section-number">2.5.2</span> Tabla de Sistemas de Coordenadas en Colombia</h3>
<table class="table">
<colgroup>
<col style="width: 38%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 23%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Nombre del Sistema</th>
<th>Tipo</th>
<th>Datum</th>
<th>Proyección</th>
<th>EPSG</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WGS 84</td>
<td>Geográfico</td>
<td>WGS84</td>
<td>—</td>
<td>4326</td>
</tr>
<tr class="even">
<td>WGS 84 / Web Mercator</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>Mercator</td>
<td>3857</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS</td>
<td>Geográfico</td>
<td>MAGNA-SIRGAS</td>
<td>—</td>
<td>4686</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS 2018 / Origen Nacional</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>9377</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Colombia Far West zone</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>3114</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Colombia West zone</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>3115</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Colombia Bogota zone</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>3116</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Colombia East Central zone</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>3117</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Colombia East zone</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>3118</td>
</tr>
<tr class="even">
<td>Bogota 1975</td>
<td>Geográfico</td>
<td>Bogotá 1975</td>
<td>—</td>
<td>4218</td>
</tr>
<tr class="odd">
<td>Bogota 1975 / Colombia West zone</td>
<td>Proyectado</td>
<td>Bogotá 1975</td>
<td>Transversa Mercator</td>
<td>21896</td>
</tr>
<tr class="even">
<td>Bogota 1975 / Colombia Bogota zone</td>
<td>Proyectado</td>
<td>Bogotá 1975</td>
<td>Transversa Mercator</td>
<td>21897</td>
</tr>
<tr class="odd">
<td>Bogota 1975 / Colombia East Central zone</td>
<td>Proyectado</td>
<td>Bogotá 1975</td>
<td>Transversa Mercator</td>
<td>21898</td>
</tr>
<tr class="even">
<td>Bogota 1975 / Colombia East zone</td>
<td>Proyectado</td>
<td>Bogotá 1975</td>
<td>Transversa Mercator</td>
<td>21899</td>
</tr>
<tr class="odd">
<td>WGS 84 / UTM 17N</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32617</td>
</tr>
<tr class="even">
<td>WGS 84 / UTM 18N</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32618</td>
</tr>
<tr class="odd">
<td>WGS 84 / UTM 19N</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32619</td>
</tr>
<tr class="even">
<td>WGS 84 / UTM 17S</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32717</td>
</tr>
<tr class="odd">
<td>WGS 84 / UTM 18S</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32718</td>
</tr>
<tr class="even">
<td>WGS 84 / UTM 19S</td>
<td>Proyectado</td>
<td>WGS84</td>
<td>UTM</td>
<td>32719</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Arauca urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6244</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Armenia urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6245</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Barranquilla urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6246</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Bogota urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6247</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Bucaramanga urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6248</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Cali urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6249</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Cartagena urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6250</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Cucuta urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6251</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Florencia urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6252</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Ibague urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6253</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Inirida urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6254</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Leticia urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6255</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Manizales urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6256</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Medellin urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6257</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Mitu urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6258</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Mocoa urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6259</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Monteria urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6260</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Neiva urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6261</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Pasto urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6262</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Pereira urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6263</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Popayan urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6264</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Puerto Carreno urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6265</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Quibdo urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6266</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Riohacha urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6267</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / San Andres urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6268</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / San Jose del Guaviare urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6269</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Santa Marta urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6270</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Sucre urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6271</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Tunja urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6272</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Valledupar urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6273</td>
</tr>
<tr class="odd">
<td>MAGNA-SIRGAS / Villavicencio urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6274</td>
</tr>
<tr class="even">
<td>MAGNA-SIRGAS / Yopal urban grid</td>
<td>Proyectado</td>
<td>MAGNA-SIRGAS</td>
<td>Transversa Mercator</td>
<td>6275</td>
</tr>
</tbody>
</table>
<hr>
<section id="comparación-técnica" class="level4" data-number="2.5.2.1">
<h4 data-number="2.5.2.1" class="anchored" data-anchor-id="comparación-técnica"><span class="header-section-number">2.5.2.1</span> Comparación Técnica</h4>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Datum Antiguo (Bogotá 1975)</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Datum Oficial (MAGNA-SIRGAS)</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<ul>
<li>Basado en el elipsoide International 1924<br>
</li>
<li>Ajustado localmente<br>
</li>
<li>No compatible directamente con GNSS moderno<br>
</li>
<li>Generaba diferencias métricas frente a sistemas globales</li>
</ul>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<ul>
<li>Compatible con sistemas GNSS<br>
</li>
<li>Marco geocéntrico<br>
</li>
<li>Adoptado oficialmente en Colombia<br>
</li>
<li>Permite integración con estándares internacionales<br>
</li>
<li>Desde 2020 opera bajo Origen Nacional único (EPSG:9377)</li>
</ul>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="transformación-de-sistemas-de-coordenadas-en-arcgis-pro" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="transformación-de-sistemas-de-coordenadas-en-arcgis-pro"><span class="header-section-number">2.6</span> Transformación de sistemas de coordenadas en ArcGIS Pro</h2>
<p>Se utilizó la herramienta <strong>Project</strong> para reproyectar:</p>
<p><code>veredas.shp (Colombia Bogota Zone)</code><br>
hacia un sistema MAGNA-SIRGAS correspondiente.</p>
<p>Nombre de salida: <code>veredas_magna</code></p>
<p>En este caso hubo cambio de datum, por tanto se aplicó transformación geográfica correspondiente a la región VIII.</p>
<section id="resultado-de-la-reproyección" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="resultado-de-la-reproyección"><span class="header-section-number">2.6.1</span> Resultado de la reproyección</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reproyeccion.jpg" class="img-fluid figure-img"></p>
<figcaption>Reproyección de veredas.shp</figcaption>
</figure>
</div>
<p>La herramienta ejecuta:</p>
<ol type="1">
<li>Conversión matemática de coordenadas planas a geográficas base.</li>
<li>Aplicación de parámetros de transformación geográfica.</li>
<li>Reproyección al sistema de salida.</li>
<li>Generación de nuevo feature class.</li>
</ol>
<hr>
</section>
</section>
<section id="usando-la-proyección-al-vuelo" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="usando-la-proyección-al-vuelo"><span class="header-section-number">2.7</span> Usando la Proyección al Vuelo</h2>
<p>Se cargó <code>cundinamarca.shp</code> en un mapa con sistema diferente.</p>
<p>ArcGIS ejecutó <strong>Proyección al Vuelo</strong>, es decir:</p>
<ul>
<li>Conversión temporal en memoria</li>
<li>Sin modificar el archivo original</li>
</ul>
<p>Posteriormente se formalizó esta reproyección exportando la capa:</p>
<p>Click derecho → Data → Export Features<br>
Seleccionando “Current Map” como sistema de salida.</p>
<section id="resultado-formalizado" class="level3" data-number="2.7.1">
<h3 data-number="2.7.1" class="anchored" data-anchor-id="resultado-formalizado"><span class="header-section-number">2.7.1</span> Resultado formalizado</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="proyeccion_al_vuelo.jpg" class="img-fluid figure-img"></p>
<figcaption>Proyección al vuelo formalizada</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="conversión-importando-a-una-geodatabase" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="conversión-importando-a-una-geodatabase"><span class="header-section-number">2.8</span> Conversión importando a una Geodatabase</h2>
<p>Se creó un Dataset dentro de la File Geodatabase:</p>
<p><code>magna_sirgas_gcs</code></p>
<p>con sistema de coordenadas geográficas MAGNA-SIRGAS.</p>
<section id="creación-del-dataset" class="level3" data-number="2.8.1">
<h3 data-number="2.8.1" class="anchored" data-anchor-id="creación-del-dataset"><span class="header-section-number">2.8.1</span> Creación del Dataset</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="dataset_magna_sirgas_gcs.jpg" class="img-fluid figure-img"></p>
<figcaption>Creación del Dataset magna_sirgas_gcs</figcaption>
</figure>
</div>
<p>Posteriormente se importó <code>veredas.shp</code> al dataset:</p>
<p>Click derecho → Import → Feature Class(es)</p>
<p>ArcGIS realizó automáticamente la conversión.</p>
</section>
<section id="importación-de-veredas-al-dataset" class="level3" data-number="2.8.2">
<h3 data-number="2.8.2" class="anchored" data-anchor-id="importación-de-veredas-al-dataset"><span class="header-section-number">2.8.2</span> Importación de veredas al Dataset</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="veredas_desde_dataset.jpg" class="img-fluid figure-img"></p>
<figcaption>Importación de veredas al dataset</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="generar-una-capa-de-puntos-desde-lista-de-coordenadas" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="generar-una-capa-de-puntos-desde-lista-de-coordenadas"><span class="header-section-number">2.9</span> Generar una capa de puntos desde lista de coordenadas</h2>
<p>Se utilizó el archivo:</p>
<p><code>coordenadas_wkid_11117_magna_sirgas_east_central.txt</code></p>
<p>Mediante la herramienta <strong>XY Table To Point</strong>.</p>
<p>Sistema asignado: MAGNA-SIRGAS correspondiente.</p>
<p>La capa fue almacenada dentro del Dataset <code>magna_sirgas_gcs</code>.</p>
<section id="resultado-de-la-generación-de-puntos" class="level3" data-number="2.9.1">
<h3 data-number="2.9.1" class="anchored" data-anchor-id="resultado-de-la-generación-de-puntos"><span class="header-section-number">2.9.1</span> Resultado de la generación de puntos</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="puntos_de_lista_de_coord.jpg" class="img-fluid figure-img"></p>
<figcaption>Puntos generados desde lista de coordenadas</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="conclusiones" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">2.10</span> Conclusiones</h2>
<ol type="1">
<li><p>La verificación inicial de los archivos permitió identificar la importancia del archivo <code>.prj</code> dentro de la estructura de un Shapefile, ya que su ausencia impide conocer el sistema de referencia espacial original.</p></li>
<li><p>La herramienta <strong>Define Projection</strong> únicamente asigna información de referencia espacial; no transforma coordenadas. Su uso incorrecto puede generar errores espaciales significativos sin que el software emita advertencias.</p></li>
<li><p>El sistema <strong>GCS_Bogota (EPSG: 4218)</strong> es geográfico y está basado en un datum local antiguo (Bogotá 1975), el cual no es compatible directamente con tecnologías GNSS modernas sin aplicar una transformación geográfica.</p></li>
<li><p>El sistema <strong>Colombia Bogota Zone (EPSG: 21891)</strong> es proyectado y deriva del mismo datum antiguo, por lo tanto no pertenece al marco geodésico oficial vigente.</p></li>
<li><p>La transformación de datos desde Bogotá 1975 hacia MAGNA-SIRGAS requiere obligatoriamente una transformación geográfica, recomendándose el modelo Molodensky-Badekas (10 parámetros) por su mayor estabilidad matemática y precisión regional.</p></li>
<li><p>La comparación de coordenadas entre capas reproyectadas evidenció diferencias métricas apreciables, confirmando que los cambios de datum pueden producir desplazamientos del orden de decenas o más de cien metros.</p></li>
<li><p>La Proyección al Vuelo permite visualización coherente entre sistemas distintos sin alterar los datos originales; sin embargo, para consolidar la transformación es necesario exportar la capa.</p></li>
<li><p>La importación de datos a una geodatabase con sistema distinto demuestra que ArcGIS Pro realiza conversiones automáticas cuando los sistemas están correctamente definidos.</p></li>
<li><p>El <strong>Origen Nacional (EPSG: 9377)</strong> representa la modernización del sistema cartográfico colombiano, al unificar el territorio bajo un único origen proyectado basado en MAGNA-SIRGAS. Su implementación reduce inconsistencias entre regiones y mejora la interoperabilidad institucional.</p></li>
<li><p>Desde el punto de vista técnico, la adopción del Origen Nacional fortalece la coherencia geométrica del país al estar vinculado a un marco geocéntrico compatible con estándares internacionales.</p></li>
<li><p>En términos geomáticos, la correcta gestión del datum y del origen cartográfico no es solamente un requisito técnico, sino un componente esencial para garantizar precisión, interoperabilidad y validez científica en cualquier proyecto espacial.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>En análisis espacial, siempre se debe verificar el EPSG antes de iniciar cualquier análisis espacial.</p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>